{% set name = "cesium" %}
{% set version = "0.12.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7b39ddf1adc325a60a57d2ced4c11ed2013245ea5d933a35ab46dbf431f3204b

build:
  number: 1
  skip: true  # [win]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - numpy >=1.14.3
    - cython
    - setuptools-scm
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.16.0
    - scikit-learn >=0.22.1
    - pandas >=0.17.0
    - dask >=2.5.0
    - toolz
    - gatspy >=0.3.0
    - cloudpickle
    - joblib >=0.14.1

test:
  imports:
    - cesium
    - cesium.datasets
    - cesium.features

about:
  home: http://cesium-ml.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Machine Learning Time-Series Platform
  doc_url: http://cesium-ml.org/docs/
  dev_url: https://github.com/cesium-ml/cesium

extra:
  recipe-maintainers:
    - cbcunc
