{% set name = "cesium" %}
{% set version = "0.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7fe0ba04f3c6eb643994e388d8915499606ebd9daa6ac899a4550989889faa8

build:
  number: 0
  skip: true  # [win]
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - pip
    - python
    - numpy >=1.14.3
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy >=0.16.0
    - scikit-learn >=0.18.1
    - pandas >=0.17.0
    - dask >=1.0.0
    - toolz
    - gatspy >=0.3.0
    - cloudpickle

test:
  imports:
    - cesium
    - cesium.datasets
    - cesium.features

about:
  home: http://cesium-ml.org/
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Machine Learning Time-Series Platform
  doc_url: http://cesium-ml.org/docs/
  dev_url: https://github.com/cesium-ml/cesium

extra:
  recipe-maintainers:
    - cbcunc
